name: Build docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Set up dependencies
        run: npm install

      - name: Build docs
        run: npm generateDocs

      - name: Commit and push changes
        run: |
            git add -A
            git commit -m "build(docs): docs rebuild by github action"
            git push
